name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install step
        run: "cd client; deno i; cd ../server; deno i"

      - name: Build step
        run: "cd client; deno run build; cp ../server/main.ts ./dist/server.ts"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "def-spacewa-web-socket-55"
          entrypoint: "./main.ts"
          root: "./client/dist/"
